### ISSUE TITLE
MouseMode fails to build

### ISSUE THREAD

**Issue by karatekidcaleb** [JupiterRider/ballntower_cs#2]
I was trying to import and build this project to get a better idea of 3D best practices in Godot (Mono) and I came across four related errors the compiler threw wehn trying to build your current code.

>/home/user/Godot/ballntower_cs/scripts/FirstPersonPlayer.cs(63,22): Member 'Input.MouseModeEnum.Captured' cannot be accessed with an instance reference; qualify it with a type name instead
>/home/user/Godot/ballntower_cs/scripts/EndMenu.cs(47,28): Member 'Input.MouseModeEnum.Visible' cannot be accessed with an instance reference; qualify it with a type name instead
>/home/user/Godot/ballntower_cs/scripts/PauseMenu.cs(65,36): Member 'Input.MouseModeEnum.Visible' cannot be accessed with an instance reference; qualify it with a type name instead
>/home/user/Godot/ballntower_cs/scripts/PauseMenu.cs(89,28): Member 'Input.MouseModeEnum.Captured' cannot be accessed with an instance reference; qualify it with a type name instead

For reference I'm building on 64-bit Mono Godot 3.5, running Ubuntu

**Comment by JupiterRider** [comment]
@karatekidcaleb I fixed it.
The original project was made with Godot 3.2. In the meantime the canged the name of the Enum from Input.MouseMode to Input.MouseModeEnum
